#+TITLE: 海龟交易系统
#+AUTHOR: 胡琛

* 一个完整交易系统构成

  1. Markets -- What to buy or sell
   
  2. Position Sizing -- How much to buy or sell

  3. Entries -- When to buy or sell

  4. Stops -- When to get out of a losing position

  5. Exits -- When to get out of a winning position

  6. Tactic -- How to buy or sell

* 海龟交易的品种要求

  海龟交易的是在美国芝加哥和纽约交易所交易的具有流动性的期货。
  
  *海龟只在流动性最好的市场进行交易。*

* 头寸规模

  *头寸规模是所有交易系统最重要的部分之一，但也是最不为人理解的部分。*
  
  海龟将一个基于波动性的常数百分比用作头寸规模风险的测算标准。

  
** 波动性 N 定义

     就是 =TR= (True Range，实际范围) 的 20 日指数移动平均，现在更普遍地称之为 =ATR= 。
     从概念上来看，N 表示单个交易日某个特定市场所造成的价格波动的平均范围，
     它说明了开盘价的缺口。N 同样用构成合约基础的点 (points) 进行度量。
  
** 价值量波动性的调整

     确定头寸规模的第一步，是确定用根本的市场价格波动性 (用其 N 值定义) 表示的价值量波动性。
     价值量波动性用下面简单的公式确定：

       \begin{equation}
         价值量波动性=N×每点价值量
       \end{equation}

** 波动性调整后的头寸单位

     海龟按照我们所称的单位 (Units) 建立头寸。单位按大小排列，使 =1N= 代表帐户净值的 $1\%$。

   因此，特定市场或特定商品的单位可用下面的公式计算：

     \begin{equation}
       单位=帐户的 1\%/市场价值量波动性
     \end{equation}
    
   或
  
     \begin{equation}
       单位=帐户的 1\%/(N×每点价值量)
     \end{equation}
    
** 头寸规模重要性

   多样化就是努力在诸多投资工具上分散风险，并且通过增加抓住成功交易的机会而增加赢利的机会。
   适当的多样化要求我们在多种不同的投资工具上进行类似的（如果不是同样的话）下注。

   海龟系统用市场波动性来度量每个市场有关的风险。然后，我们用这一风险量度标准以表示风险
   （或波动性）的一个常数的增量来建立头寸。这提高了多样化的收益，并且增加了赢利交易弥补亏损交易的可能性。

   注意：这种多样化在资金不足时很难实现。
   
** 作为风险量度标准的单位

   因为海龟把单位用作头寸规模的量度基础，还因为那些单位已经过波动性风险调整，所以，单位既是头寸风险的量度标准，又是头寸整个投资组合的量度标准。

   海龟被给予限制我们可以在任何特定的时间在四个不同的级别上持仓的单位数目的风险管理法则。本质上，这些法则控制着交易员可能带来的全部风险，这些限制在亏损延长期间以及价格异常波动期间使损失最小化。

   最大头寸限制为：

   | 级别 | 类型                | 最大单位 |
   |------+---------------------+----------|
   |    1 | 单一市场            | 4 个单位  |
   |    2 | 高度相关市场        | 6 个单位  |
   |    3 | 低度相关市场        | 10 个单位 |
   |    4 | 单向交易—多头或空头 | 12 个单位 |
  
   - 单一市场：每个市场最大为 4 个单位
   - 高度相关市场：对于高度相关的市场，在一个特定方向上最大可以有 6 个单位（即，6 个多头单位或 6 个空头单位）。高度相关市场包括：
     - 燃油和原油
     - 黄金和白银
     - 瑞士法郎和德国马克
     - 短期国库券和欧洲美元
   - 低度相关市场：对于低度相关的市场，在一个特定方向上最大可以有 10 个单位。低度相关市场包括：
     - 黄金和铜
     - 白银和铜
     - 很多因头寸限制而海龟不能进行交易的谷物组合
   - 单一方向：在一个多头方向或一个空头方向上全部单位的最大数目为 12。因此，理论上你可以同时持有 12 个单位的多头头寸和 12 个单位的空头头寸。

** 调整交易规模
   
   海龟不使用以起始净值为基础的、连续结算的标准帐户进行交易。我们得到一个起始净值为零、有明确的帐户规模的虚拟帐户。
   
   每当原始帐户亏损 $10\%$ 时，海龟就得到指示，将虚拟帐户的规模减小 $20\%$ 。因此，如果某个交易 100 万美元帐户的海龟曾经亏损 $10\%$ ，
   即 10 万美元，那 么，我们就开始交易好象只有 80 万美元的帐户，直到我们达到每年的起始净值为止。如果我们再亏损 $10\%$ (80 万的 $10\%$ 即 8 万美元，总亏损为 18 万美元)，
   我们就要再减小虚拟帐户规模为 64 万美元的帐户规模的 $20\%$ 。
   
   随着帐户的增长或下降，对于减小或增大净值还有别的或许更好的策略。这些就是海龟所用的法则。

* 入市

  海龟用两个相关的系统入市，这两个系统都以唐奇安的通道突破系统（Donchian’s channel breakout system）为基础。
  
  海龟总是在日间突破发生时进行交易，而不会等到每日收盘或次日开盘。在开盘跳空的情况下，如果市场开盘超过了突破的价位，海龟一开盘就会建立头寸。
  
** 突破
  
*** 系统一： 以 20 日突破为基础的偏短线系统
   
    只要有一个信号显示价格超过前 20 天的最高价或最低价，海龟就会建立头寸。如果价格超过 20 天的最高价，那么，海龟就会在相应的商品上买入一个单位，
    建立多头头寸。如果有一个信号显示价格跌破了最近 20 天的最低价，海龟就会卖出一个单位建立空头头寸。
   
    如果上次突破已导致赢利的交易，系统一的突破入市信号就会被忽视。注意：为了检验这个问题，上次突破被视为某种商品上最近一次的突破，
    而不管对那次突破是否实际被接受，或者因这项法则而被忽略。如果有赢利的 10 日离市之前，突破日之后的价格与头寸方向相反波动了 2N，
    那么，这一突破就会被视为失败的突破。
   
    上次突破的方向与这项法则无关。因此，亏损的多头突破或亏损的空头突破将使随后新的突破被视为有效的突破，而不管它的方向如何（即多头或空头）。
   
    此外，如果系统一的入市突破由于以前的交易已经取得赢利而被忽略，还可以在 55 日突破时入市，以避免错过主要的波动。
    这种 55 日突破被视为自动保险突破点(Failsafe Breakout point)。
   
    如果你还没有入市，在任何特定点位都会有一些价位会触发空头入市，在另外一些不同的较高价位会触发多头入市。如果上次突破失败，那么，
    入市信号会更接近于现价（即，20 日突破），如果上次突破成功，在这种情况下入市信号可能会远得多，位于 55 日突破处。

*** 系统二： 以 50 日突破为基础的较简单的长线系统
   
    只要有一个信号显示价格超过了前 55 日的最高价或最低价就建立头寸。如果价格超过 55 日最高价，那么，海龟就会在相应的商品上买入一个
    单位建立多头头寸。如果有一个信号显示价格跌破了最近 55 日的最低价，海龟就会卖出一个单位建立空头头寸。
   
    无论以前的突破是成功还是失败，所有系统二的突破都会被接受。

** 加仓

   海龟在突破时只建立一个单位的多头头寸，在建立头寸后以 1/2N（即二分之一 N----译注）的间隔增加头寸。这种 1/2N 的间隔以前面指令的实际成交价为基础。
   因此，如果初始突破指令降低了 1/2N，那么，为了说明 1/2N 的降低，新指令就是突破后的 1N 加上正常的 1/2N 个单位的增加间隔。在达到最大许可单位数之前，
   这样都是正确的。如果市场波动很快，有可能在一天之内就增加到最大 4 个单位。

** 连续性

   海龟被告知在接受入市信号时要非常连续，因为一年中大部分利润可能仅仅来自于两三次大的赢利交易。如果一个信号被忽略或错过，就可能极大地影响全年度的收益。

* 止损
  
  海龟以头寸风险为基础设置止损。任何一笔交易都不能出现 $2\%$ 以上的风险。 因为价格波动 1N 表示 $1\%$ 的帐户净值，
  容许风险为 $2\%$ 的最大止损就是价格波动 2N。海龟的止损设置在多头头寸入市价格以下的 2N，空头头寸入市价格以上的 2N。 

  为了保证全部头寸的风险最小，如果另外增加单位，前面单位的止损就提高 1/2N。这一般意味着全部头寸的止损将被设置在踞最近
  增加的单位的 2N 处。然而，在后面单位因市场波动太快造成“打滑（skid）”或者因开盘跳空而以较大的间隔设置的情况下，止损
  就有所不同。
* 离市
  
** 系统一 

   离市对于多头头寸为 10 日最低价，对于空头头寸为 10 日最高价。如果价格波动与头寸背离至 10 日突破，头寸中的所有单位都会退出。

** 系统二
   
   对于多头头寸为 20 日最低价，对于空头头寸为 20 日最高价。如果价格波动与头寸背离至 20 日突破，头寸中的所有单位都会退出。
* 总结 

  理查德.丹尼斯说过的话：“我总是说你们可以在报纸上发表我的交易法则，没有人会遵循它们。关键在于连续性和纪律。几乎任何人都能够罗列一张交易法 则的清单，其中的 $80\%$ 
  与我们教授给我们的学员的一样。他们所不能做的是带给他们自信，甚至在情况恶化时仍坚持那些法则。”----摘自《华尔街点金 人》，约翰.施瓦格。 
